version: '3.3'
services:
  epicgames-freegames:
    environment:
      - TZ=America/Nassau
    volumes:
      - './config:/usr/app/config:rw'
    image: charlocharlie/epicgames-freegames
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.epic.rule=Host(`epic.${REVERSE_HOST}`)"
      - "traefik.http.routers.epic.entrypoints=web-secure"
      - "traefik.http.routers.epic.tls=true"
    networks: 
      - reverse

networks:
  reverse:
    external:
      name: reverse