version: '3.3'
services:
  portainer:
    ports:
      - '8000:8000'
      - '9000:9000'
    container_name: portainer
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './portainer_data:/data'
    image: portainer/portainer-ce
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`port.${REVERSE_HOST}`)"
      - "traefik.http.routers.portainer.entrypoints=web-secure"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    networks: 
      - reverse


networks:
  reverse:
    external:
      name: reverse