version: '3.3'
services:
  xbackbone-docker:
    ports:
        - '9080:80'
    environment:
        - APP_NAME=XBackBone
        #- 'URL=https:\/\/img.bastion.thebritishaccent.net'
        - 'URL=https:\/\/xbb.thebritishaccent.net'
        - 'PHP_UPLOAD_MAX_FILESIZE=2G'
        - 'PHP_POST_MAX_SIZE=2G'
    volumes:
        - ./storage:/app/storage
        - xbb_database:/app/resources/database
        - xbb_logs:/app/logs
        - ./config:/app/config
    container_name: xbb
    image: pe46dro/xbackbone-docker
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.xbb.rule=Host(`xbb.${REVERSE_HOST}`)"
      - "traefik.http.routers.xbb.entrypoints=web-secure"
      - "traefik.http.routers.xbb.tls=true"
    networks: 
      - reverse

volumes:
  xbb_database:
  xbb_logs:

networks:
  reverse:
    external:
      name: reverse