---
version: "2.1"
services:
  dashmachine:
    image: rmountjoy/dashmachine0.7:latest
    container_name: dashmachine0.7
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Nassau
      - EDITOR_URL=https://code.tba.lan/?workspace=/data/dashmachine/config/dashmachine.code-workspace
    volumes:
      - ./config:/DashMachine/config
    ports:
      - 5001:5000
    restart: unless-stopped
