---
version: "2"
services:
  bookstack:
    image: linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=<DBPASSWORD>
      - DB_DATABASE=bookstackapp
      - APP_URL="https://bookstack.thebritishaccent.net"
    volumes:
      - ./bookstack-data:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=<ROOTPASSWORD>
      - TZ=America/Nassau
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=<DBPASSWORD>
    volumes:
      - ./mariadb-data:/config
    restart: unless-stopped

